"""Evaluate a YOLOv8 detection model and generate common research plots.

What this script produces:
- Precision-Recall curve and confusion matrix: generated by Ultralytics' built-in validator (plots=True)
- ROC curve (optional): image-level *presence* ROC per class

Notes on ROC:
Object detection typically reports PR/mAP rather than ROC because the notion of
"true negatives" is ill-defined for localization tasks. The ROC produced here is
therefore computed at image level (presence/absence of a class in an image).

Example:
  python scripts/evaluate_model.py --model runs/train/exp/weights/best.pt --data data_template.yaml --roc
"""

from __future__ import annotations

import argparse
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, Iterable, List, Sequence, Tuple

import numpy as np


IMG_EXTS = {".jpg", ".jpeg", ".png", ".bmp", ".tif", ".tiff", ".webp"}


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description="Evaluate YOLOv8 model and generate plots")
    p.add_argument("--model", required=True, help="Path to YOLOv8 .pt weights")
    p.add_argument("--data", required=True, help="Path to data YAML (train/val/nc/names)")
    p.add_argument("--imgsz", type=int, default=640, help="Inference/val image size")
    p.add_argument("--conf", type=float, default=0.25, help="Confidence threshold for Ultralytics val")
    p.add_argument("--iou", type=float, default=0.5, help="IoU threshold")
    p.add_argument("--device", default=None, help="Device, e.g. 0, 'cpu'. Defaults to Ultralytics")
    p.add_argument("--project", default="runs/eval", help="Output folder base")
    p.add_argument("--name", default="exp", help="Run name")
    p.add_argument(
        "--roc",
        action="store_true",
        help="Also generate ROC curve (image-level presence) and AUC summary",
    )
    p.add_argument(
        "--classes",
        default="",
        help="Optional class filter by indices, e.g. '0,7' (limits val/predict/ROC to these class IDs)",
    )
    p.add_argument(
        "--epp-only",
        action="store_true",
        help="Shortcut to evaluate only helmet/hardhat and vest/safety vest (resolved by class names in data YAML)",
    )
    p.add_argument(
        "--core-only",
        action="store_true",
        help="Shortcut to evaluate only person + helmet/hardhat + vest/safety vest (resolved by class names in data YAML)",
    )
    p.add_argument(
        "--split",
        default="val",
        choices=["train", "val", "test"],
        help="Which split in the data YAML to use for ROC computation",
    )
    p.add_argument(
        "--roc-conf",
        type=float,
        default=0.001,
        help="Low conf used when predicting for ROC scoring (keeps more boxes)",
    )
    return p.parse_args()


def _match_any(name: str, keywords: Sequence[str]) -> bool:
    n = name.lower()
    return any(k in n for k in keywords)


def _parse_classes_arg(s: str) -> List[int]:
    s = (s or "").strip()
    if not s:
        return []
    out: List[int] = []
    for part in s.split(","):
        part = part.strip()
        if not part:
            continue
        out.append(int(part))
    return sorted(set(out))


def _resolve_class_names(data_dict: dict) -> List[str]:
    names = data_dict.get("names")
    if isinstance(names, dict):
        # YAML may store names as {0: 'person', 1: 'helmet', ...}
        return [names[k] for k in sorted(names.keys(), key=lambda x: int(x))]
    if isinstance(names, (list, tuple)):
        return [str(x) for x in names]
    nc = int(data_dict.get("nc", 0) or 0)
    return [str(i) for i in range(nc)]


def _resolve_epp_class_indices(class_names: Sequence[str]) -> List[int]:
    helmet_keys = ["helmet", "hardhat", "hard hat", "casco"]
    vest_keys = ["vest", "safety vest", "chaleco"]

    def is_negative(n: str) -> bool:
        s = n.lower().replace("_", " ").replace("-", " ").strip()
        return s.startswith("no ") or s.startswith("sin ")

    idxs: List[int] = []
    for i, n in enumerate(class_names):
        if is_negative(n):
            continue
        if _match_any(n, helmet_keys) or _match_any(n, vest_keys):
            idxs.append(i)
    return sorted(set(idxs))


def _resolve_core_class_indices(class_names: Sequence[str]) -> List[int]:
    person_keys = ["person", "persona", "worker", "trabajador"]
    helmet_keys = ["helmet", "hardhat", "hard hat", "casco"]
    vest_keys = ["vest", "safety vest", "chaleco"]

    def is_negative(n: str) -> bool:
        s = n.lower().replace("_", " ").replace("-", " ").strip()
        return s.startswith("no ") or s.startswith("sin ")

    idxs: List[int] = []
    for i, n in enumerate(class_names):
        if is_negative(n):
            continue
        if _match_any(n, person_keys) or _match_any(n, helmet_keys) or _match_any(n, vest_keys):
            idxs.append(i)

    return sorted(set(idxs))


def _import_ultralytics():
    try:
        from ultralytics import YOLO  # type: ignore

        return YOLO
    except Exception as e:  # pragma: no cover
        raise RuntimeError(
            "ultralytics is not available. Install it in your venv: pip install ultralytics"
        ) from e


def _import_yaml():
    try:
        import yaml  # type: ignore

        return yaml
    except Exception as e:  # pragma: no cover
        raise RuntimeError("PyYAML is required. Install: pip install pyyaml") from e


def _is_image(p: Path) -> bool:
    return p.suffix.lower() in IMG_EXTS


def _as_path(p: str, base: Path) -> Path:
    pp = Path(p)
    if pp.is_absolute():
        return pp
    return (base / pp).resolve()


def _resolve_data_root(data_dict: dict, yaml_path: Path) -> Path:
    base = yaml_path.parent
    root = data_dict.get("path")
    if root:
        return _as_path(str(root), base)
    return base


def _iter_images_from_split(split_value, root: Path) -> List[Path]:
    paths: List[Path] = []

    if split_value is None:
        return paths

    def add_from_one(v) -> None:
        p = _as_path(str(v), root)
        if p.is_dir():
            paths.extend([x for x in p.rglob("*") if x.is_file() and _is_image(x)])
        elif p.is_file():
            if p.suffix.lower() == ".txt":
                # file with one image path per line
                for line in p.read_text(encoding="utf-8", errors="ignore").splitlines():
                    line = line.strip()
                    if not line:
                        continue
                    img_p = _as_path(line, p.parent)
                    if img_p.is_file() and _is_image(img_p):
                        paths.append(img_p)
            else:
                if _is_image(p):
                    paths.append(p)

    if isinstance(split_value, (list, tuple)):
        for v in split_value:
            add_from_one(v)
    else:
        add_from_one(split_value)

    # stable order
    paths = sorted(set(paths))
    return paths


def _image_to_label_path(image_path: Path) -> Path:
    parts = list(image_path.parts)
    try:
        idx = parts.index("images")
        parts[idx] = "labels"
        return Path(*parts).with_suffix(".txt")
    except ValueError:
        # fallback heuristics
        candidate = image_path.with_suffix(".txt")
        if candidate.exists():
            return candidate
        # try sibling labels folder
        return (image_path.parent.parent / "labels" / image_path.name).with_suffix(".txt")


def _load_present_classes(label_path: Path) -> List[int]:
    if not label_path.exists():
        return []

    present: List[int] = []
    for line in label_path.read_text(encoding="utf-8", errors="ignore").splitlines():
        line = line.strip()
        if not line:
            continue
        # YOLO: cls x y w h
        try:
            cls_id = int(float(line.split()[0]))
        except Exception:
            continue
        present.append(cls_id)
    return present


def _compute_roc_points(y_true: np.ndarray, y_score: np.ndarray) -> Tuple[np.ndarray, np.ndarray, float]:
    """Compute ROC curve points and AUC (binary)."""

    if y_true.ndim != 1 or y_score.ndim != 1:
        raise ValueError("y_true and y_score must be 1D arrays")

    # thresholds from scores (descending)
    thresholds = np.unique(y_score)[::-1]
    if thresholds.size == 0:
        thresholds = np.array([0.0])

    tpr_list: List[float] = []
    fpr_list: List[float] = []

    for thr in thresholds:
        y_pred = y_score >= thr

        tp = float(np.sum((y_pred == 1) & (y_true == 1)))
        fp = float(np.sum((y_pred == 1) & (y_true == 0)))
        tn = float(np.sum((y_pred == 0) & (y_true == 0)))
        fn = float(np.sum((y_pred == 0) & (y_true == 1)))

        tpr = tp / (tp + fn) if (tp + fn) > 0 else 0.0
        fpr = fp / (fp + tn) if (fp + tn) > 0 else 0.0

        tpr_list.append(tpr)
        fpr_list.append(fpr)

    fpr = np.array(fpr_list, dtype=float)
    tpr = np.array(tpr_list, dtype=float)

    # sort by fpr for auc
    order = np.argsort(fpr)
    fpr_s = fpr[order]
    tpr_s = tpr[order]
    # NumPy 2.x removed np.trapz; prefer np.trapezoid when available.
    trapezoid = getattr(np, "trapezoid", None)
    if trapezoid is not None:
        auc = float(trapezoid(tpr_s, fpr_s))
    else:  # pragma: no cover
        auc = float(np.trapz(tpr_s, fpr_s))
    return fpr_s, tpr_s, auc


def main() -> int:
    args = parse_args()

    YOLO = _import_ultralytics()
    yaml = _import_yaml()

    data_yaml = Path(args.data).resolve()
    if not data_yaml.exists():
        raise FileNotFoundError(f"Data YAML not found: {data_yaml}")

    data_dict = yaml.safe_load(data_yaml.read_text(encoding="utf-8")) or {}

    class_names = _resolve_class_names(data_dict)
    if not class_names:
        raise RuntimeError("Could not determine class names from data YAML (names/nc)")

    selected_classes = _parse_classes_arg(args.classes)
    if args.core_only:
        selected_classes = _resolve_core_class_indices(class_names)
        if not selected_classes:
            raise RuntimeError(
                "--core-only could not find person/helmet/vest classes in data YAML names. "
                "Use --classes 'i,j,k' explicitly, or update names in the YAML."
            )
    elif args.epp_only:
        selected_classes = _resolve_epp_class_indices(class_names)
        if not selected_classes:
            raise RuntimeError(
                "--epp-only could not find helmet/vest classes in data YAML names. "
                "Use --classes 'i,j' explicitly, or update names in the YAML."
            )

    project_dir = Path(args.project).resolve()
    out_dir = project_dir / args.name
    out_dir.mkdir(parents=True, exist_ok=True)

    model = YOLO(args.model)

    # 1) Ultralytics built-in validation (generates PR curve, confusion matrix, etc.)
    val_kwargs = {
        "data": str(data_yaml),
        "imgsz": int(args.imgsz),
        "conf": float(args.conf),
        "iou": float(args.iou),
        "plots": True,
        "project": str(project_dir),
        "name": str(args.name),
    }
    if selected_classes:
        val_kwargs["classes"] = selected_classes
    if args.device is not None:
        val_kwargs["device"] = args.device

    val_res = model.val(**val_kwargs)

    # Try to discover where Ultralytics saved plots
    save_dir = getattr(val_res, "save_dir", None)
    if save_dir:
        out_dir = Path(save_dir)

    if not args.roc:
        print(f"[OK] Validation finished. Plots saved to: {out_dir}")
        return 0

    # 2) Image-level presence ROC
    root = _resolve_data_root(data_dict, data_yaml)
    split_value = data_dict.get(args.split)
    image_paths = _iter_images_from_split(split_value, root)

    if not image_paths:
        raise RuntimeError(
            f"No images found for split '{args.split}'. Check the YAML field '{args.split}' in {data_yaml}"
        )

    all_class_names = class_names
    all_nc = len(all_class_names)
    if all_nc <= 0:
        raise RuntimeError("Could not determine number of classes from data YAML (names/nc)")

    if selected_classes:
        keep = selected_classes
    else:
        keep = list(range(all_nc))

    keep = [c for c in keep if 0 <= c < all_nc]
    if not keep:
        raise RuntimeError("Selected class filter is empty after validation")

    kept_names = [str(all_class_names[c]) for c in keep]
    id_to_pos: Dict[int, int] = {cls_id: j for j, cls_id in enumerate(keep)}

    y_true = np.zeros((len(image_paths), len(keep)), dtype=np.int32)
    y_score = np.zeros((len(image_paths), len(keep)), dtype=np.float32)

    print(f"Computing ROC (image-level presence) on {len(image_paths)} images...")

    for i, img_path in enumerate(image_paths):
        label_path = _image_to_label_path(img_path)
        present_cls = set(_load_present_classes(label_path))
        for c in present_cls:
            pos = id_to_pos.get(c)
            if pos is not None:
                y_true[i, pos] = 1

        preds = model.predict(
            source=str(img_path),
            imgsz=int(args.imgsz),
            conf=float(args.roc_conf),
            iou=float(args.iou),
            classes=keep,
            device=args.device,
            verbose=False,
        )
        if not preds:
            continue

        r0 = preds[0]
        boxes = getattr(r0, "boxes", None)
        if boxes is None:
            continue

        try:
            cls_arr = boxes.cls.cpu().numpy().astype(int)
            conf_arr = boxes.conf.cpu().numpy().astype(float)
        except Exception:
            # very defensive fallback
            cls_arr = np.array([], dtype=int)
            conf_arr = np.array([], dtype=float)

        for cls_id, pos in id_to_pos.items():
            mask = cls_arr == cls_id
            if np.any(mask):
                y_score[i, pos] = float(np.max(conf_arr[mask]))

    # Plot ROC
    import matplotlib.pyplot as plt  # imported late to keep startup fast

    auc_rows: List[Tuple[str, float]] = []

    plt.figure(figsize=(7, 6))
    for c, name in enumerate(kept_names):
        fpr, tpr, auc = _compute_roc_points(y_true[:, c], y_score[:, c])
        auc_rows.append((str(name), float(auc)))
        plt.plot(fpr, tpr, linewidth=2, label=f"{name} (AUC={auc:.3f})")

    plt.plot([0, 1], [0, 1], "--", linewidth=1, color="gray")
    plt.xlim([0.0, 1.0])
    plt.ylim([0.0, 1.05])
    plt.xlabel("False Positive Rate (FPR)")
    plt.ylabel("True Positive Rate (TPR / Recall)")
    plt.title("ROC curve (image-level presence)")
    plt.grid(True, alpha=0.3)
    plt.legend(loc="lower right", fontsize=9)

    roc_path = out_dir / "roc_curve_presence.png"
    plt.tight_layout()
    plt.savefig(roc_path, dpi=200)
    plt.close()

    # Save AUC summary
    auc_csv = out_dir / "roc_auc_presence.csv"
    with auc_csv.open("w", encoding="utf-8") as f:
        f.write("class,auc\n")
        for cls_name, auc in auc_rows:
            f.write(f"{cls_name},{auc:.6f}\n")

    print(f"[OK] Validation plots saved to: {out_dir}")
    print(f"[OK] ROC saved to: {roc_path}")
    print(f"[OK] ROC AUC summary saved to: {auc_csv}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
